<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            ['code' => 'AF', 'name_en' => 'Afghanistan', 'name_ar' => 'أفغانستان',],
            ['code' => 'AL', 'name_en' => 'Albania', 'name_ar' => 'ألبانيا',],
            ['code' => 'AX', 'name_en' => 'Aland Islands', 'name_ar' => 'جزر آلاند',],
            ['code' => 'DZ', 'name_en' => 'Algeria', 'name_ar' => 'الجزائر',],
            ['code' => 'AS', 'name_en' => 'American Samoa', 'name_ar' => 'ساموا-الأمريكي',],
            ['code' => 'AD', 'name_en' => 'Andorra', 'name_ar' => 'أندورا',],
            ['code' => 'AO', 'name_en' => 'Angola', 'name_ar' => 'أنغولا',],
            ['code' => 'AI', 'name_en' => 'Anguilla', 'name_ar' => 'أنغويلا',],
            ['code' => 'AQ', 'name_en' => 'Antarctica', 'name_ar' => 'أنتاركتيكا',],
            ['code' => 'AG', 'name_en' => 'Antigua and Barbuda', 'name_ar' => 'أنتيغوا وبربودا',],
            ['code' => 'AR', 'name_en' => 'Argentina', 'name_ar' => 'الأرجنتين',],
            ['code' => 'AM', 'name_en' => 'Armenia', 'name_ar' => 'أرمينيا',],
            ['code' => 'AW', 'name_en' => 'Aruba', 'name_ar' => 'أروبه',],
            ['code' => 'AU', 'name_en' => 'Australia', 'name_ar' => 'أستراليا',],
            ['code' => 'AT', 'name_en' => 'Austria', 'name_ar' => 'النمسا',],
            ['code' => 'AZ', 'name_en' => 'Azerbaijan', 'name_ar' => 'أذربيجان',],
            ['code' => 'BS', 'name_en' => 'Bahamas', 'name_ar' => 'الباهاماس',],
            ['code' => 'BH', 'name_en' => 'Bahrain', 'name_ar' => 'البحرين',],
            ['code' => 'BD', 'name_en' => 'Bangladesh', 'name_ar' => 'بنغلاديش',],
            ['code' => 'BB', 'name_en' => 'Barbados', 'name_ar' => 'بربادوس',],
            ['code' => 'BY', 'name_en' => 'Belarus', 'name_ar' => 'روسيا البيضاء',],
            ['code' => 'BE', 'name_en' => 'Belgium', 'name_ar' => 'بلجيكا',],
            ['code' => 'BZ', 'name_en' => 'Belize', 'name_ar' => 'بيليز',],
            ['code' => 'BJ', 'name_en' => 'Benin', 'name_ar' => 'بنين',],
            ['code' => 'BL', 'name_en' => 'Saint Barthelemy', 'name_ar' => 'سان بارتيلمي',],
            ['code' => 'BM', 'name_en' => 'Bermuda', 'name_ar' => 'جزر برمودا',],
            ['code' => 'BT', 'name_en' => 'Bhutan', 'name_ar' => 'بوتان',],
            ['code' => 'BO', 'name_en' => 'Bolivia', 'name_ar' => 'بوليفيا',],
            ['code' => 'BA', 'name_en' => 'Bosnia and Herzegovina', 'name_ar' => 'البوسنة و الهرسك',],
            ['code' => 'BW', 'name_en' => 'Botswana', 'name_ar' => 'بوتسوانا',],
            ['code' => 'BV', 'name_en' => 'Bouvet Island', 'name_ar' => 'جزيرة بوفيه',],
            ['code' => 'BR', 'name_en' => 'Brazil', 'name_ar' => 'البرازيل',],
            ['code' => 'IO', 'name_en' => 'British Indian Ocean Territory', 'name_ar' => 'إقليم المحيط الهندي البريطاني',],
            ['code' => 'BN', 'name_en' => 'Brunei Darussalam', 'name_ar' => 'بروني',],
            ['code' => 'BG', 'name_en' => 'Bulgaria', 'name_ar' => 'بلغاريا',],
            ['code' => 'BF', 'name_en' => 'Burkina Faso', 'name_ar' => 'بوركينا فاسو',],
            ['code' => 'BI', 'name_en' => 'Burundi', 'name_ar' => 'بوروندي',],
            ['code' => 'KH', 'name_en' => 'Cambodia', 'name_ar' => 'كمبوديا',],
            ['code' => 'CM', 'name_en' => 'Cameroon', 'name_ar' => 'كاميرون',],
            ['code' => 'CA', 'name_en' => 'Canada', 'name_ar' => 'كندا',],
            ['code' => 'CV', 'name_en' => 'Cape Verde', 'name_ar' => 'الرأس الأخضر',],
            ['code' => 'KY', 'name_en' => 'Cayman Islands', 'name_ar' => 'جزر كايمان',],
            ['code' => 'CF', 'name_en' => 'Central African Republic', 'name_ar' => 'جمهورية أفريقيا الوسطى',],
            ['code' => 'TD', 'name_en' => 'Chad', 'name_ar' => 'تشاد',],
            ['code' => 'CL', 'name_en' => 'Chile', 'name_ar' => 'شيلي',],
            ['code' => 'CN', 'name_en' => 'China', 'name_ar' => 'الصين',],
            ['code' => 'CX', 'name_en' => 'Christmas Island', 'name_ar' => 'جزيرة عيد الميلاد',],
            ['code' => 'CC', 'name_en' => 'Cocos (Keeling) Islands', 'name_ar' => 'جزر كوكوس',],
            ['code' => 'CO', 'name_en' => 'Colombia', 'name_ar' => 'كولومبيا',],
            ['code' => 'KM', 'name_en' => 'Comoros', 'name_ar' => 'جزر القمر',],
            ['code' => 'CG', 'name_en' => 'Congo', 'name_ar' => 'الكونغو',],
            ['code' => 'CK', 'name_en' => 'Cook Islands', 'name_ar' => 'جزر كوك',],
            ['code' => 'CR', 'name_en' => 'Costa Rica', 'name_ar' => 'كوستاريكا',],
            ['code' => 'HR', 'name_en' => 'Croatia', 'name_ar' => 'كرواتيا',],
            ['code' => 'CU', 'name_en' => 'Cuba', 'name_ar' => 'كوبا',],
            ['code' => 'CY', 'name_en' => 'Cyprus', 'name_ar' => 'قبرص',],
            ['code' => 'CW', 'name_en' => 'Curaçao', 'name_ar' => 'كوراساو',],
            ['code' => 'CZ', 'name_en' => 'Czech Republic', 'name_ar' => 'الجمهورية التشيكية',],
            ['code' => 'DK', 'name_en' => 'Denmark', 'name_ar' => 'الدانمارك',],
            ['code' => 'DJ', 'name_en' => 'Djibouti', 'name_ar' => 'جيبوتي',],
            ['code' => 'DM', 'name_en' => 'Dominica', 'name_ar' => 'دومينيكا',],
            ['code' => 'DO', 'name_en' => 'Dominican Republic', 'name_ar' => 'الجمهورية الدومينيكية',],
            ['code' => 'EC', 'name_en' => 'Ecuador', 'name_ar' => 'إكوادور',],
            ['code' => 'EG', 'name_en' => 'Egypt', 'name_ar' => 'مصر',],
            ['code' => 'SV', 'name_en' => 'El Salvador', 'name_ar' => 'إلسلفادور',],
            ['code' => 'GQ', 'name_en' => 'Equatorial Guinea', 'name_ar' => 'غينيا الاستوائي',],
            ['code' => 'ER', 'name_en' => 'Eritrea', 'name_ar' => 'إريتريا',],
            ['code' => 'EE', 'name_en' => 'Estonia', 'name_ar' => 'استونيا',],
            ['code' => 'ET', 'name_en' => 'Ethiopia', 'name_ar' => 'أثيوبيا',],
            ['code' => 'FK', 'name_en' => 'Falkland Islands (Malvinas)', 'name_ar' => 'جزر فوكلاند',],
            ['code' => 'FO', 'name_en' => 'Faroe Islands', 'name_ar' => 'جزر فارو',],
            ['code' => 'FJ', 'name_en' => 'Fiji', 'name_ar' => 'فيجي',],
            ['code' => 'FI', 'name_en' => 'Finland', 'name_ar' => 'فنلندا',],
            ['code' => 'FR', 'name_en' => 'France', 'name_ar' => 'فرنسا',],
            ['code' => 'GF', 'name_en' => 'French Guiana', 'name_ar' => 'غويانا الفرنسية',],
            ['code' => 'PF', 'name_en' => 'French Polynesia', 'name_ar' => 'بولينيزيا الفرنسية',],
            ['code' => 'TF', 'name_en' => 'French Southern and Antarctic Lands', 'name_ar' => 'أراض فرنسية جنوبية وأنتارتيكية',],
            ['code' => 'GA', 'name_en' => 'Gabon', 'name_ar' => 'الغابون',],
            ['code' => 'GM', 'name_en' => 'Gambia', 'name_ar' => 'غامبيا',],
            ['code' => 'GE', 'name_en' => 'Georgia', 'name_ar' => 'جيورجيا',],
            ['code' => 'DE', 'name_en' => 'Germany', 'name_ar' => 'ألمانيا',],
            ['code' => 'GH', 'name_en' => 'Ghana', 'name_ar' => 'غانا',],
            ['code' => 'GI', 'name_en' => 'Gibraltar', 'name_ar' => 'جبل طارق',],
            ['code' => 'GG', 'name_en' => 'Guernsey', 'name_ar' => 'غيرنزي',],
            ['code' => 'GR', 'name_en' => 'Greece', 'name_ar' => 'اليونان',],
            ['code' => 'GL', 'name_en' => 'Greenland', 'name_ar' => 'جرينلاند',],
            ['code' => 'GD', 'name_en' => 'Grenada', 'name_ar' => 'غرينادا',],
            ['code' => 'GP', 'name_en' => 'Guadeloupe', 'name_ar' => 'جزر جوادلوب',],
            ['code' => 'GU', 'name_en' => 'Guam', 'name_ar' => 'جوام',],
            ['code' => 'GT', 'name_en' => 'Guatemala', 'name_ar' => 'غواتيمال',],
            ['code' => 'GN', 'name_en' => 'Guinea', 'name_ar' => 'غينيا',],
            ['code' => 'GW', 'name_en' => 'Guinea-Bissau', 'name_ar' => 'غينيا-بيساو',],
            ['code' => 'GY', 'name_en' => 'Guyana', 'name_ar' => 'غيانا',],
            ['code' => 'HT', 'name_en' => 'Haiti', 'name_ar' => 'هايتي',],
            ['code' => 'HM', 'name_en' => 'Heard and Mc Donald Islands', 'name_ar' => 'جزيرة هيرد وجزر ماكدونالد',],
            ['code' => 'HN', 'name_en' => 'Honduras', 'name_ar' => 'هندوراس',],
            ['code' => 'HK', 'name_en' => 'Hong Kong', 'name_ar' => 'هونغ كونغ',],
            ['code' => 'HU', 'name_en' => 'Hungary', 'name_ar' => 'المجر',],
            ['code' => 'IS', 'name_en' => 'Iceland', 'name_ar' => 'آيسلندا',],
            ['code' => 'IN', 'name_en' => 'India', 'name_ar' => 'الهند',],
            ['code' => 'IM', 'name_en' => 'Isle of Man', 'name_ar' => 'جزيرة مان',],
            ['code' => 'ID', 'name_en' => 'Indonesia', 'name_ar' => 'أندونيسيا',],
            ['code' => 'IR', 'name_en' => 'Iran', 'name_ar' => 'إيران',],
            ['code' => 'IQ', 'name_en' => 'Iraq', 'name_ar' => 'العراق',],
            ['code' => 'IE', 'name_en' => 'Ireland', 'name_ar' => 'إيرلندا',],
            ['code' => 'IL', 'name_en' => 'Israel', 'name_ar' => 'إسرائيل',],
            ['code' => 'IT', 'name_en' => 'Italy', 'name_ar' => 'إيطاليا',],
            ['code' => 'CI', 'name_en' => 'Ivory Coast', 'name_ar' => 'ساحل العاج',],
            ['code' => 'JE', 'name_en' => 'Jersey', 'name_ar' => 'جيرزي',],
            ['code' => 'JM', 'name_en' => 'Jamaica', 'name_ar' => 'جمايكا',],
            ['code' => 'JP', 'name_en' => 'Japan', 'name_ar' => 'اليابان',],
            ['code' => 'JO', 'name_en' => 'Jordan', 'name_ar' => 'الأردن',],
            ['code' => 'KZ', 'name_en' => 'Kazakhstan', 'name_ar' => 'كازاخستان',],
            ['code' => 'KE', 'name_en' => 'Kenya', 'name_ar' => 'كينيا',],
            ['code' => 'KI', 'name_en' => 'Kiribati', 'name_ar' => 'كيريباتي',],
            ['code' => 'KP', 'name_en' => 'Korea(North Korea)', 'name_ar' => 'كوريا الشمالية',],
            ['code' => 'KR', 'name_en' => 'Korea(South Korea)', 'name_ar' => 'كوريا الجنوبية', ],
            ['code' => 'XK', 'name_en' => 'Kosovo', 'name_ar' => 'كوسوفو', ],
            ['code' => 'KW', 'name_en' => 'Kuwait', 'name_ar' => 'الكويت', ],
            ['code' => 'KG', 'name_en' => 'Kyrgyzstan', 'name_ar' => 'قيرغيزستان', ],
            ['code' => 'LA', 'name_en' => 'Lao PDR', 'name_ar' => 'لاوس', ],
            ['code' => 'LV', 'name_en' => 'Latvia', 'name_ar' => 'لاتفيا', ],
            ['code' => 'LB', 'name_en' => 'Lebanon', 'name_ar' => 'لبنان', ],
            ['code' => 'LS', 'name_en' => 'Lesotho', 'name_ar' => 'ليسوتو', ],
            ['code' => 'LR', 'name_en' => 'Liberia', 'name_ar' => 'ليبيريا', ],
            ['code' => 'LY', 'name_en' => 'Libya', 'name_ar' => 'ليبيا', ],
            ['code' => 'LI', 'name_en' => 'Liechtenstein', 'name_ar' => 'ليختنشتين',],
            ['code' => 'LT', 'name_en' => 'Lithuania', 'name_ar' => 'لتوانيا', ],
            ['code' => 'LU', 'name_en' => 'Luxembourg', 'name_ar' => 'لوكسمبورغ', ],
            ['code' => 'LK', 'name_en' => 'Sri Lanka', 'name_ar' => 'سريلانكا', ],
            ['code' => 'MO', 'name_en' => 'Macau', 'name_ar' => 'ماكاو', ],
            ['code' => 'MK', 'name_en' => 'Macedonia', 'name_ar' => 'مقدونيا', ],
            ['code' => 'MG', 'name_en' => 'Madagascar', 'name_ar' => 'مدغشقر', ],
            ['code' => 'MW', 'name_en' => 'Malawi', 'name_ar' => 'مالاوي', ],
            ['code' => 'MY', 'name_en' => 'Malaysia', 'name_ar' => 'ماليزيا', ],
            ['code' => 'MV', 'name_en' => 'Maldives', 'name_ar' => 'المالديف', ],
            ['code' => 'ML', 'name_en' => 'Mali', 'name_ar' => 'مالي', ],
            ['code' => 'MT', 'name_en' => 'Malta', 'name_ar' => 'مالطا', ],
            ['code' => 'MH', 'name_en' => 'Marshall Islands', 'name_ar' => 'جزر مارشال', ],
            ['code' => 'MQ', 'name_en' => 'Martinique', 'name_ar' => 'مارتينيك', ],
            ['code' => 'MR', 'name_en' => 'Mauritania', 'name_ar' => 'موريتانيا', ],
            ['code' => 'MU', 'name_en' => 'Mauritius', 'name_ar' => 'موريشيوس', ],
            ['code' => 'YT', 'name_en' => 'Mayotte', 'name_ar' => 'مايوت', ],
            ['code' => 'MX', 'name_en' => 'Mexico', 'name_ar' => 'المكسيك', ],
            ['code' => 'FM', 'name_en' => 'Micronesia', 'name_ar' => 'مايكرونيزيا', ],
            ['code' => 'MD', 'name_en' => 'Moldova', 'name_ar' => 'مولدافيا', ],
            ['code' => 'MC', 'name_en' => 'Monaco', 'name_ar' => 'موناكو', ],
            ['code' => 'MN', 'name_en' => 'Mongolia', 'name_ar' => 'منغوليا', ],
            ['code' => 'ME', 'name_en' => 'Montenegro', 'name_ar' => 'الجبل الأسود', ],
            ['code' => 'MS', 'name_en' => 'Montserrat', 'name_ar' => 'مونتسيرات', ],
            ['code' => 'MA', 'name_en' => 'Morocco', 'name_ar' => 'المغرب', ],
            ['code' => 'MZ', 'name_en' => 'Mozambique', 'name_ar' => 'موزمبيق', ],
            ['code' => 'MM', 'name_en' => 'Myanmar', 'name_ar' => 'ميانمار', ],
            ['code' => 'NA', 'name_en' => 'Namibia', 'name_ar' => 'ناميبيا', ],
            ['code' => 'NR', 'name_en' => 'Nauru', 'name_ar' => 'نورو',],
            ['code' => 'NP', 'name_en' => 'Nepal', 'name_ar' => 'نيبال', ],
            ['code' => 'NL', 'name_en' => 'Netherlands', 'name_ar' => 'هولندا', ],
            ['code' => 'AN', 'name_en' => 'Netherlands Antilles', 'name_ar' => 'جزر الأنتيل الهولندي', ],
            ['code' => 'NC', 'name_en' => 'New Caledonia', 'name_ar' => 'كاليدونيا الجديدة', ],
            ['code' => 'NZ', 'name_en' => 'New Zealand', 'name_ar' => 'نيوزيلندا', ],
            ['code' => 'NI', 'name_en' => 'Nicaragua', 'name_ar' => 'نيكاراجوا', ],
            ['code' => 'NE', 'name_en' => 'Niger', 'name_ar' => 'النيجر', ],
            ['code' => 'NG', 'name_en' => 'Nigeria', 'name_ar' => 'نيجيريا', ],
            ['code' => 'NU', 'name_en' => 'Niue', 'name_ar' => 'ني', ],
            ['code' => 'NF', 'name_en' => 'Norfolk Island', 'name_ar' => 'جزيرة نورفولك', ],
            ['code' => 'MP', 'name_en' => 'Northern Mariana Islands', 'name_ar' => 'جزر ماريانا الشمالية', ],
            ['code' => 'NO', 'name_en' => 'Norway', 'name_ar' => 'النرويج', ],
            ['code' => 'OM', 'name_en' => 'Oman', 'name_ar' => 'عمان', ],
            ['code' => 'PK', 'name_en' => 'Pakistan', 'name_ar' => 'باكستان', ],
            ['code' => 'PW', 'name_en' => 'Palau', 'name_ar' => 'بالاو', ],
            ['code' => 'PS', 'name_en' => 'Palestine', 'name_ar' => 'فلسطين', ],
            ['code' => 'PA', 'name_en' => 'Panama', 'name_ar' => 'بنما', ],
            ['code' => 'PG', 'name_en' => 'Papua New Guinea', 'name_ar' => 'بابوا غينيا الجديدة', ],
            ['code' => 'PY', 'name_en' => 'Paraguay', 'name_ar' => 'باراغواي', ],
            ['code' => 'PE', 'name_en' => 'Peru', 'name_ar' => 'بيرو', ],
            ['code' => 'PH', 'name_en' => 'Philippines', 'name_ar' => 'الفليبين', ],
            ['code' => 'PN', 'name_en' => 'Pitcairn', 'name_ar' => 'بيتكيرن', ],
            ['code' => 'PL', 'name_en' => 'Poland', 'name_ar' => 'بولندا',],
            ['code' => 'PT', 'name_en' => 'Portugal', 'name_ar' => 'البرتغال',],
            ['code' => 'PR', 'name_en' => 'Puerto Rico', 'name_ar' => 'بورتو ريكو', ],
            ['code' => 'QA', 'name_en' => 'Qatar', 'name_ar' => 'قطر', ],
            ['code' => 'RE', 'name_en' => 'Reunion Island', 'name_ar' => 'ريونيون', ],
            ['code' => 'RO', 'name_en' => 'Romania', 'name_ar' => 'رومانيا', ],
            ['code' => 'RU', 'name_en' => 'Russian', 'name_ar' => 'روسيا',],
            ['code' => 'RW', 'name_en' => 'Rwanda', 'name_ar' => 'رواندا', ],
            ['code' => 'KN', 'name_en' => 'Saint Kitts and Nevis', 'name_ar' => 'سانت كيتس ونيفس,', ],
            ['code' => 'MF', 'name_en' => 'Saint Martin (French part)', 'name_ar' => 'ساينت مارتن فرنسي', ],
            ['code' => 'SX', 'name_en' => 'Sint Maarten (Dutch part)', 'name_ar' => 'ساينت مارتن هولندي',],
            ['code' => 'LC', 'name_en' => 'Saint Pierre and Miquelon', 'name_ar' => 'سان بيير وميكلون', ],
            ['code' => 'VC', 'name_en' => 'Saint Vincent and the Grenadines', 'name_ar' => 'سانت فنسنت وجزر غرينادين', ],
            ['code' => 'WS', 'name_en' => 'Samoa', 'name_ar' => 'ساموا',  ],
            ['code' => 'SM', 'name_en' => 'San Marino', 'name_ar' => 'سان مارينو', ],
            ['code' => 'ST', 'name_en' => 'Sao Tome and Principe', 'name_ar' => 'ساو تومي وبرينسيبي', ],
            ['code' => 'SA', 'name_en' => 'Saudi Arabia', 'name_ar' => 'المملكة العربية السعودية',],
            ['code' => 'SN', 'name_en' => 'Senegal', 'name_ar' => 'السنغال', ],
            ['code' => 'RS', 'name_en' => 'Serbia', 'name_ar' => 'صربيا',],
            ['code' => 'SC', 'name_en' => 'Seychelles', 'name_ar' => 'سيشيل', ],
            ['code' => 'SL', 'name_en' => 'Sierra Leone', 'name_ar' => 'سيراليون', ],
            ['code' => 'SG', 'name_en' => 'Singapore', 'name_ar' => 'سنغافورة', ],
            ['code' => 'SK', 'name_en' => 'Slovakia', 'name_ar' => 'سلوفاكيا', ],
            ['code' => 'SI', 'name_en' => 'Slovenia', 'name_ar' => 'سلوفينيا', ],
            ['code' => 'SB', 'name_en' => 'Solomon Islands', 'name_ar' => 'جزر سليمان', ],
            ['code' => 'SO', 'name_en' => 'Somalia', 'name_ar' => 'الصومال'],
            ['code' => 'ZA', 'name_en' => 'South Africa', 'name_ar' => 'جنوب أفريقيا', ],
            ['code' => 'GS', 'name_en' => 'South Georgia and the South Sandwich', 'name_ar' => 'المنطقة القطبية الجنوبية', ],
            ['code' => 'SS', 'name_en' => 'South Sudan', 'name_ar' => 'السودان الجنوبي', ],
            ['code' => 'ES', 'name_en' => 'Spain', 'name_ar' => 'إسبانيا', ],
            ['code' => 'SH', 'name_en' => 'Saint Helena', 'name_ar' => 'سانت هيلانة', ],
            ['code' => 'SD', 'name_en' => 'Sudan', 'name_ar' => 'السودان', ],
            ['code' => 'SR', 'name_en' => 'Suriname', 'name_ar' => 'سورينام', ],
            ['code' => 'SJ', 'name_en' => 'Svalbard and Jan Mayen', 'name_ar' => 'سفالبارد ويان ماين', ],
            ['code' => 'SZ', 'name_en' => 'Swaziland', 'name_ar' => 'سوازيلند', ],
            ['code' => 'SE', 'name_en' => 'Sweden', 'name_ar' => 'السويد',],
            ['code' => 'CH', 'name_en' => 'Switzerland', 'name_ar' => 'سويسرا', ],
            ['code' => 'SY', 'name_en' => 'Syria', 'name_ar' => 'سوريا',],
            ['code' => 'TW', 'name_en' => 'Taiwan', 'name_ar' => 'تايوان', ],
            ['code' => 'TJ', 'name_en' => 'Tajikistan', 'name_ar' => 'طاجيكستان', ],
            ['code' => 'TZ', 'name_en' => 'Tanzania', 'name_ar' => 'تنزانيا', ],
            ['code' => 'TH', 'name_en' => 'Thailand', 'name_ar' => 'تايلندا', ],
            ['code' => 'TL', 'name_en' => 'Timor-Leste', 'name_ar' => 'تيمور الشرقية', ],
            ['code' => 'TG', 'name_en' => 'Togo', 'name_ar' => 'توغو', ],
            ['code' => 'TK', 'name_en' => 'Tokelau', 'name_ar' => 'توكيلاو', ],
            ['code' => 'TO', 'name_en' => 'Tonga', 'name_ar' => 'تونغا', ],
            ['code' => 'TT', 'name_en' => 'Trinidad and Tobago', 'name_ar' => 'ترينيداد وتوباغو', ],
            ['code' => 'TN', 'name_en' => 'Tunisia', 'name_ar' => 'تونس',],
            ['code' => 'TR', 'name_en' => 'Turkey', 'name_ar' => 'تركيا', ],
            ['code' => 'TM', 'name_en' => 'Turkmenistan', 'name_ar' => 'تركمانستان', ],
            ['code' => 'TC', 'name_en' => 'Turks and Caicos Islands', 'name_ar' => 'جزر توركس وكايكوس',],
            ['code' => 'TV', 'name_en' => 'Tuvalu', 'name_ar' => 'توفالو', ],
            ['code' => 'UG', 'name_en' => 'Uganda', 'name_ar' => 'أوغندا', ],
            ['code' => 'UA', 'name_en' => 'Ukraine', 'name_ar' => 'أوكرانيا', ],
            ['code' => 'AE', 'name_en' => 'United Arab Emirates', 'name_ar' => 'الإمارات العربية المتحدة', ],
            ['code' => 'GB', 'name_en' => 'United Kingdom', 'name_ar' => 'المملكة المتحدة', ],
            ['code' => 'US', 'name_en' => 'United States', 'name_ar' => 'الولايات المتحدة', ],
            ['code' => 'UM', 'name_en' => 'US Minor Outlying Islands', 'name_ar' => 'قائمة الولايات والمناطق الأمريكية', ],
            ['code' => 'UY', 'name_en' => 'Uruguay', 'name_ar' => 'أورغواي', ],
            ['code' => 'UZ', 'name_en' => 'Uzbekistan', 'name_ar' => 'أوزباكستان', ],
            ['code' => 'VU', 'name_en' => 'Vanuatu', 'name_ar' => 'فانواتو', ],
            ['code' => 'VE', 'name_en' => 'Venezuela', 'name_ar' => 'فنزويلا', ],
            ['code' => 'VN', 'name_en' => 'Vietnam', 'name_ar' => 'فيتنام', ],
            ['code' => 'VI', 'name_en' => 'Virgin Islands (U.S.)', 'name_ar' => 'الجزر العذراء الأمريكي', ],
            ['code' => 'VA', 'name_en' => 'Vatican City', 'name_ar' => 'فاتيكان', ],
            ['code' => 'WF', 'name_en' => 'Wallis and Futuna Islands', 'name_ar' => 'والس وفوتونا', ],
            ['code' => 'EH', 'name_en' => 'Western Sahara', 'name_ar' => 'الصحراء الغربية', ],
            ['code' => 'YE', 'name_en' => 'Yemen', 'name_ar' => 'اليمن', ],
            ['code' => 'ZM', 'name_en' => 'Zambia', 'name_ar' => 'زامبيا', ],
            ['code' => 'ZW', 'name_en' => 'Zimbabwe', 'name_ar' => 'زمبابوي', ],
        ];
        Country::insert($countries);
    }
}
